details:
    page_title: Benchmark DataBoard
layout:
    - row_1_of_2:
        - col_1_of_2:
            - tile_template: just_value
              tile_id: error
              title: Error
              classes:

        - col_1_of_2:
            - tile_template: listing
              tile_id: list_devices
              title: Devices
              classes:
    - row_1_of_2:
        - col_1_of_4 flip-time-20:
            - tile_template: norm_chart
              tile_id: cpu
              title: cpu
              classes:

            - tile_template: listing
              tile_id: cpu_list
              title: Moyenne CPU
              classes:

        - col_1_of_4 flip-time-20:
            - tile_template: norm_chart
              tile_id: gcu
              title: GPU
              classes:

            - tile_template: listing
              tile_id: gpu_list
              title: Moyenne GPU
              classes:

        - col_1_of_4 flip-time-20:
            - tile_template: norm_chart
              tile_id: network
              title: network
              classes:

            - tile_template: listing
              tile_id: network_list
              title: Moyenne Network
              classes:

        - col_1_of_4:
            - tile_template: listing
              tile_id: battery
              title: Battery
              classes: