include:
  - project: adeotech/lmfr/datatech/lmfr-datatech-gitlab-ci
    file: DockerCI.gitlab-ci.yml


stages:
  - test_src
  - unit_test
  - push_registry
  - trigger_deploy


push_jfrog_dev:
  stage: push_registry
  extends: .ci_jfrog
  only: ['feat/benchmark']
  variables:
    JFROG_DOCKER_URL: ${JFROG_DOCKER_DEV_URL}
    IMAGE_NAME: ${JFROG_DOCKER_DEV_URL}/lmfr-datatech-mobility-tipboard-benchmark:dev


push_img_to_jfrog_release:
  stage: push_registry
  extends: .ci_jfrog
  only: ['master']
  variables:
    JFROG_DOCKER_URL: ${JFROG_DOCKER_RELEASE_URL}
    IMAGE_NAME: ${JFROG_DOCKER_RELEASE_URL}/lmfr-datatech-mobility-tipboard-benchmark:master

deploy_preprod:
  stage: trigger_deploy
  extends: .pipepline_trigger
  only: ['dev']
  variables:
    WEB_HOOK: curl -X POST -F token=${TOKEN_WEBHOOK} -F ref=develop https://gitlab.com/api/v4/projects/17036390/trigger/pipeline

deploy_prod:
  stage: trigger_deploy
  extends: .pipepline_trigger
  only: ['feat/benchmark']
  variables:
    WEB_HOOK: curl -X POST -F token=${TOKEN_WEBHOOK} -F ref=master https://gitlab.com/api/v4/projects/17036390/trigger/pipeline
